name: pyffp
channels:
- conda-forge
dependencies:
        # core dependencies
        - python>3
        - pytest
        - pip
        - numpy
        - matplotlib
        - scipy        
        # extras
        - jupyterlab
        - folium
        - geopandas
        - geopy
        - pip
        - pip:
                - geojsoncontour
